from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.urls import reverse_lazy

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('blog/', views.blog, name='blog'),
    path('dashboard/', views.patient_dashboard, name='patient_dashboard'),
    path('doctors/<str:hospital_name>/', views.doctor_list, name='doctor_list'),
    path('doctor/<int:doctor_id>/', views.doctor_profile, name='doctor_profile'),
    path('appointments/', views.my_appointments, name='my_appointments'),
    path('medical-records/', views.medical_records, name='medical_records'),
    path('appointment/book/<int:doctor_id>/', views.appointment_form, name='appointment_form'),
    path('appointment/book/', views.appointment_form, name='appointment_form_no_doctor'),
    path('appointment/payment/', views.payment, name='payment'),
    path('appointment/success/<int:appointment_id>/', views.success, name='appointment_success'),
    path('appointment/cancel/<int:appointment_id>/', views.cancel_appointment, name='cancel_appointment'),
    path('appointment/reschedule/<int:appointment_id>/', views.reschedule_appointment, name='reschedule_appointment'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/hospital/add/', views.dashboard_add_hospital, name='dashboard_add_hospital'),
    path('hospital/<int:hospital_id>/doctor/add/', views.add_doctor_for_hospital, name='add_doctor_for_hospital'),
    path('doctor/<int:doctor_id>/delete/from/<str:hospital_name>/', views.delete_doctor_from_list, name='delete_doctor_from_list'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/add/<int:medicine_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:medicine_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('payment/<str:order_type>/<int:order_id>/', views.payment, name='payment_specific'),
    path('medicine/payment/', views.payment, name='medicine_payment'),
    path('admin/hospitals/', views.admin_hospital_list, name='admin_hospital_list'),
    path('admin/hospitals/create/', views.admin_hospital_create, name='admin_hospital_create'),
    path('admin/hospitals/<int:pk>/edit/', views.admin_hospital_update, name='admin_hospital_update'),
    path('admin/hospitals/<int:pk>/delete/', views.admin_hospital_delete, name='admin_hospital_delete'),
    path('admin/doctors/', views.admin_doctor_list, name='admin_doctor_list'),
    path('admin/doctors/create/', views.admin_doctor_create, name='admin_doctor_create'),
    path('admin/doctors/<int:pk>/edit/', views.admin_doctor_update, name='admin_doctor_update'),
    path('admin/doctors/<int:pk>/delete/', views.admin_doctor_delete, name='admin_doctor_delete'),
    path('admin/appointments/', views.admin_appointment_list, name='admin_appointment_list'),
    path('admin/appointments/<int:pk>/edit/', views.admin_appointment_update, name='admin_appointment_update'),
    path('admin/appointments/<int:pk>/delete/', views.admin_appointment_delete, name='admin_appointment_delete'),
    path('medicine/', views.medicine_list, name='medicine_list'),
    path('medicine/order/', views.order_medicine, name='order_medicine'),
    path('medicine/orders/', views.my_medicine_orders, name='my_medicine_orders'),
    path('medicine/order/success/', views.medicine_order_success, name='medicine_order_success'),
    path('medicine/delete/<int:medicine_id>/', views.delete_medicine, name='delete_medicine'),
    path('medicine/fetch-external/', views.fetch_external_medicines, name='fetch_external_medicines'),
]