# Generated by Django 5.2 on 2025-04-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_labtestcategory_labtest_labtestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='test_category',
        ),
        migrations.RemoveField(
            model_name='labtestresult',
            name='lab_test',
        ),
        migrations.DeleteModel(
            name='LabTestCategory',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='LabTestResult',
        ),
    ]
