# Generated by Django 5.2 on 2025-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_relationship',
        ),
    ]
